changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: User-facing changes
      labels:
        - enhancement
        - feature
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Tests and CI
      labels:
        - tests
        - ci
    - title: Maintenance
      labels:
        - maintenance
        - refactor
    - title: Other changes
      labels:
        - "*"
